spring:
  datasource:
    url: jdbc:h2:mem:app
    username: sa
    password:
    platform: h2
#  datasource:
#    url: jdbc:mysql://azimuthapp.pl:3306/messagesDatabase?useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: Very.Strong.Password
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /console
      enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 3600s
server:
  port: 8080